In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
a

array([-0.38239917,  0.0264644 ,  0.01136627,  0.8113693 , -2.13492063])

In [4]:
expa = np.exp(a)

In [5]:
expa

array([0.68222267, 1.02681769, 1.01143111, 2.25098815, 0.11825398])

In [6]:
answer = expa/expa.sum()

In [7]:
answer

array([0.1340395 , 0.20174371, 0.19872063, 0.44226224, 0.02323392])

In [8]:
answer.sum()

1.0

In [9]:
#100 samples with 5 classes
A = np.random.randn(100, 5)

In [11]:
#To make it all positive
expA = np.exp(A)
expA

array([[ 2.78971838,  0.79124461,  3.73682742,  0.17937076,  0.59094302],
       [ 0.90656268,  0.77490978,  0.77691864,  0.75599078,  0.56946466],
       [ 0.25578148,  2.30300498,  0.50145854,  0.2343424 ,  0.68234799],
       [ 0.18804763,  0.82540684,  0.20550861,  1.48236618,  4.84567193],
       [ 4.20332097,  0.31915952,  1.54364106,  2.0327057 ,  0.73567075],
       [ 0.31844864,  2.58704412,  3.14525001,  1.03484307,  1.60521711],
       [ 0.2712237 ,  2.03113825,  4.19690912,  0.83646802,  6.77195275],
       [ 1.49879085,  3.06161759,  2.96558742,  0.25736629,  1.08761043],
       [ 0.16920935,  1.32323238,  0.29375248,  1.19220221, 10.40668582],
       [11.21928258,  1.3579719 ,  1.85917556,  1.7743205 ,  0.67034239],
       [ 5.78655032,  0.1741087 ,  1.07527182,  3.61858492,  1.09147242],
       [ 1.14853996,  0.28511863,  2.06903919,  1.74021515,  1.31784076],
       [ 0.22535504,  1.44466878,  0.98730915,  3.58427369,  0.1645912 ],
       [ 0.5344443 ,  0.19691102,  0.6

In [14]:
expA.sum(axis=1, keepdims=True)

array([[ 8.08810418],
       [ 3.78384655],
       [ 3.97693539],
       [ 7.54700119],
       [ 8.83449799],
       [ 8.69080296],
       [14.10769183],
       [ 8.87097258],
       [13.38508225],
       [16.88109294],
       [11.74598818],
       [ 6.56075369],
       [ 6.40619786],
       [ 6.10747882],
       [ 4.21719823],
       [ 1.73869347],
       [ 2.50473428],
       [ 1.67118227],
       [ 9.03288114],
       [ 5.35519867],
       [11.78668861],
       [11.65101964],
       [ 7.10900593],
       [ 4.6043476 ],
       [ 7.12410461],
       [ 4.8218298 ],
       [ 8.30648149],
       [ 3.14652961],
       [ 4.24386185],
       [10.48252548],
       [ 6.81370902],
       [ 3.56598855],
       [ 5.56914596],
       [ 3.52402907],
       [ 4.55534879],
       [ 5.47822032],
       [ 8.64832018],
       [ 6.3039148 ],
       [ 5.37650122],
       [ 8.19321028],
       [ 5.62542972],
       [ 5.33368862],
       [ 8.17811268],
       [ 8.62291998],
       [10.64366253],
       [ 6

In [21]:
expA.sum(axis=1).shape

(100,)

In [22]:
expA.sum(axis=1, keepdims=True).shape

(100, 1)

In [23]:
answer = expA / expA.sum(axis=1, keepdims=True)
answer

array([[0.34491623, 0.09782819, 0.46201524, 0.02217711, 0.07306323],
       [0.23958759, 0.20479419, 0.20532509, 0.19979425, 0.15049888],
       [0.06431623, 0.57909037, 0.1260917 , 0.05892537, 0.17157633],
       [0.02491687, 0.10936885, 0.0272305 , 0.19641791, 0.64206588],
       [0.47578493, 0.0361265 , 0.17472878, 0.23008729, 0.0832725 ],
       [0.03664203, 0.29767608, 0.36190557, 0.11907336, 0.18470297],
       [0.01922524, 0.14397382, 0.29749084, 0.05929163, 0.48001848],
       [0.16895451, 0.34512761, 0.3343024 , 0.02901218, 0.12260329],
       [0.01264164, 0.09885874, 0.02194626, 0.08906947, 0.77748389],
       [0.66460641, 0.08044336, 0.1101336 , 0.10510697, 0.03970966],
       [0.49264057, 0.01482282, 0.09154375, 0.30806986, 0.092923  ],
       [0.1750622 , 0.04345821, 0.31536608, 0.26524623, 0.20086728],
       [0.03517766, 0.22551111, 0.1541178 , 0.55950093, 0.02569249],
       [0.08750653, 0.03224097, 0.1007788 , 0.30791349, 0.4715602 ],
       [0.07635291, 0.22468955, 0.

In [17]:
answer.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])